"use client";
import { api } from "@/lib/api";
import { useAnalysis, ContextToolbar, ModelWarning } from "@/components/AnalysisContext";
import { useResource } from "@/hooks/useResource";
import { ErrorNotice, Loading } from "@/components/Feedback";
export default function Analysis() {
  const ctx = useAnalysis();
  const resource = useResource(ctx.run?.id || "methodology", () => api.getPipelineMetadata(ctx.run?.id), !ctx.loading && !ctx.error);
  const metadata = resource.data;
  return <><div className="page-heading"><div><p className="eyebrow">Methodology & evidence</p><h1>Analysis</h1><p className="muted">Local batch NLP, model provenance and the limits of interpretation.</p></div></div><ContextToolbar filters={false} /><ModelWarning /><ErrorNotice error={ctx.error || resource.error} retry={() => { ctx.refresh(); resource.retry(); }} />{resource.loading && <Loading />}
    <section className="panel"><h2>How a dataset becomes evidence</h2><ol className="method-steps"><li><strong>Validate and import.</strong> Preserve original text, normalize timestamps to UTC, retain duplicate rows with explicit warnings and import only valid rows.</li><li><strong>Preprocess.</strong> Normalize Unicode and whitespace, replace URLs and mentions, demojize and retain extracted hashtags. Original posts remain available.</li><li><strong>Predict sentiment.</strong> CardiffNLP Twitter-RoBERTa produces positive, neutral and negative scores on CPU. Missing weights fail the run with a recovery message.</li><li><strong>Discover topics.</strong> MiniLM semantic vectors, seeded UMAP and HDBSCAN discover natural clusters; c-TF-IDF supplies terms. Dataset-relative sizing and conservative centroid consolidation reduce fragmentation while preserving raw provenance. Corpora below 15 posts use an explicitly recorded agglomerative method.</li><li><strong>Enrich and score.</strong> spaCy extracts filtered entities when installed. Corpus TF-IDF and hashtag frequencies support investigation. UTC buckets include zero-activity gaps through the dataset’s latest timestamp.</li></ol></section>
    {metadata && <><section className="panel"><h2>Model and execution status</h2><dl className="evidence-list"><div><dt>Sentiment · {metadata.sentiment_license}</dt><dd>{metadata.sentiment_model}</dd></div><div><dt>Embeddings · Apache-2.0</dt><dd>{metadata.embedding_model} · {metadata.embedding_dimensions} dimensions</dd></div><div><dt>Entities · MIT</dt><dd>{metadata.ner_model} · {metadata.ner_status.status || "not loaded"}</dd></div><div><dt>Topic model · MIT</dt><dd>{metadata.topic_model}</dd></div><div><dt>Preprocessing</dt><dd>{metadata.preprocessing_version}</dd></div><div><dt>Database</dt><dd>{metadata.database_backend}</dd></div><div><dt>Current analysis job</dt><dd>{metadata.active_run ? `${metadata.active_run.status} · ${metadata.active_run.current_step} · ${metadata.active_run.progress_pct}%` : "No active job"}</dd></div></dl>{metadata.ner_status.warning && <p className="notice">{metadata.ner_status.warning}</p>}<details><summary>Installed package versions</summary><dl className="evidence-list">{Object.entries(metadata.package_versions).map(([name, version]) => <div key={name}><dt>{name}</dt><dd className="numeric">{version}</dd></div>)}</dl></details></section>
      <section className="panel"><h2>TrendScore and classification</h2><p className="numeric formula">M = 0.35 × volume + 0.25 × engagement + 0.20 × velocity + 0.20 × burst; TrendScore = 0.5 + (M − 0.5) × recency</p><p>Signals are normalized to [0, 1]. Missing engagement redistributes its weight. Recency uses the dataset’s latest timestamp, so historical uploads are evaluated consistently. Sentiment describes the topic and does not contribute to this score.</p><p>Classification applies growth and score thresholds after the minimum volume guard. Fewer than {metadata.min_posts_for_trend} current posts forces Stable, even if the score is high. Emerging requires new activity; Rising and Declining reflect the implemented thresholds. There is no separate Burst classification.</p><details><summary>Weights and thresholds</summary><pre className="json-evidence">{JSON.stringify({ weights: metadata.trend_weights, thresholds: metadata.trend_thresholds, minimum_posts: metadata.min_posts_for_trend }, null, 2)}</pre></details></section>
      <section className="panel"><h2>Selected run evidence</h2>{ctx.run ? <><p className="numeric">{ctx.run.id} · {ctx.run.status}</p><details open><summary>Recorded model configuration and status</summary><pre className="json-evidence">{JSON.stringify(metadata.run_model_info, null, 2)}</pre></details><details><summary>Processing and evaluation statistics</summary><pre className="json-evidence">{JSON.stringify(metadata.run_stats, null, 2)}</pre></details></> : <p>No selected analysis run. Import and analyze a dataset to record execution evidence.</p>}<p className="muted">Synthetic trend labels describe the demo generator. They do not validate sentiment accuracy or generalize to real populations. No benchmark accuracy is claimed without independent annotated ground truth.</p></section></>}
  </>;
}
